### ISSUE TITLE
Shield Ethernet

### ISSUE THREAD

**Issue by Anderson69s** [bgaultier/laboite#1]
Bonjour, comment allez-vous? 

Petite question, comme le shield ethernet arrive en fin de vie, pensez adapter d'autres cartes arduino qui peuvent ce connecter à internet?

**Comment by bgaultier** [comment]
Salut,

Je travaille en ce moment sur une version basée sur le module ESP8266. Ça devrait sortir en septembre. Sinon j'ai déjà une version wifi Électric Imp de fonctionnelle si ça t'intéresse ?

À bientôt
